config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects do
    resources :collaborations, only: [:new, :create, :show, :index]

    resources :comments, only: [:index, :show, :new, :create]
    resources :hacker_days, only: [:new, :create, :show, :update,:destroy, :index]
    resources :likes
    resources :team_comments, only: [:index, :show, :new, :create]

  end

  resources :users, only: :show do
    resources :notifications, only: :index
  end

  post 'users/:user_id/notifications', to: 'notifications#mark_as_read', as: :notifications_mark_as_read


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :show ]
      resources :projects, only: [ :index, :show, :update, :create, :destory ] do
        resources :hacker_days, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :comments, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :likes, only: [ :index, :show, :new, :create, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  # acts_as_taggable_on :tags
  mount_uploader :avatar, AvatarUploader
  has_many :projects
  has_many :collaborations
  has_many :comments
  has_many :team_comments
  has_many :notifications, dependent: :destroy, foreign_key: :recipient_id
  has_many :likes, dependent: :destroy

  validates :email, :username, uniqueness: true, presence: true
  # validates :avatar, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers: [:github]

  # def self.from_omniauth(auth)
  #   where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
  #     user.email = auth.info.email
  #     user.password = Devise.friendly_token[0, 20]
  #     user.username = auth.info.nickname
  #     user.social_avatar = auth.info.image
  #     # assuming the user model has a name
  #     # user.image = auth.info.image # assuming the user model has an image
  #     # If you are using confirmable and the provider(s) you use validate emails,
  #     # uncomment the line below to skip the confirmation emails.
  #     # user.skip_confirmation!
  #   end
  # end

  def self.new_with_session(params, session)
    super.tap do |user|
      if data = session["devise.github_data"] && session["devise.github_data"]["extra"]["raw_info"]
        user.email = data["email"] if user.email.blank?
      end
    end
  end

  def profile_avatar_url
    social_avatar || avatar.url(:bright_face)
  end

  def self.from_omniauth(auth)
    puts auth
    user_params = auth.info.slice("email")
    # user_params[:provider] = auth.provider
    # user_params[:uid] = auth.uid
    user_params[:username] = auth.info.nickname
    user_params[:social_avatar] = auth.info.image
    user_params[:city] = auth.extra.raw_info.location
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20] # Fake password for validation
      user.save
    end

    return user
  end

  # def self.find_for_facebook_oauth(auth)
  #   user_params = auth.slice("provider", "uid")
  #   user_params.merge! auth.info.slice("email", "first_name", "last_name")
  #   user_params[:facebook_picture_url] = auth.info.image
  #   user_params[:token] = auth.credentials.token
  #   user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
  #   user_params = user_params.to_h

  #   user = User.find_by(provider: auth.provider, uid: auth.uid)
  #   user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
  #   if user
  #     user.update(user_params)
  #   else
  #     user = User.new(user_params)
  #     user.password = Devise.friendly_token[0,20]  # Fake password for validation
  #     user.save
  #   end

  #   return user
  # end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < Api::V1::BaseController
  def show
    @user = User.find(params[:id])
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  def github
    # You need to implement the method below in your model (e.g. app/models/user.rb)
    @user = User.from_omniauth(request.env["omniauth.auth"])
    if @user.persisted?
      sign_in_and_redirect @user, event: :authentication #this will throw if @user is not activated
      set_flash_message(:notice, :success, kind: "Github") if is_navigational_format?
    else
      session["devise.github_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:avatar])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    authorize @user
    @sessions_array = []
    HackerDay.all.each do |x|
      if x.attendants.include?(@user.id.to_s)
        @sessions_array << x
      end
    end
    # authorize @project
    # @hacker_days = HackerDay.find(params[:id])
  end
end

app/views/users/show.html.erb
<div class="container">
  <div class="row" style="justify-content: center;">

    <div class="col-md-4">
      <div class="box-user-profile">
        <div class="container">
          <%= link_to user_path(@user) do %>
          <img src="<%= @user.profile_avatar_url %>" class="avatar-large">
          <h5><%= @user.username %></h5>
          <% end %>
          <div class="location">
            <i class="fas fa-map-marker-alt"></i> | <%= @user.city %>, <%= @user.country %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-8">
      <div class="container">
        <div class="card-section-header">
          <h5>My Projects</h5>
        </div>
        <div class="row">
          <% if @user.projects.empty? %>
            <p class="d-flex w-100 justify-content-center font-italic mt-3">No current active projects.</p>
          <% else %>
            <% @user.projects.each do |project| %>
            <div class="col-xl-6">
              <%= link_to project_path(project) do %>
                <div class="card">
                  <%= cl_image_tag project.cover_photo, crop: :fill, alt: "image", class: "card-img-top" %>
                  <div class="card-body">
                    <div class="card-content-header">
                      <h6><%= project.name %></h6>
                      <div class="box-list-inline">
                        <i class="fas fa-comment-dots"></i>
                        <p><%= project.comments.size %></p>
                        <i class="fas fa-heart"></i>
                        <p><%= project.likes.size %></p>
                      </div>
                    </div>
                  </div>
                </div>
              <% end %>
            </div>
            <% end %>
          <% end %>
        </div>

        <div class="card-section-header" style="margin-bottom: 16px;">
          <h5>My Upcoming Hack Sessions</h5>
        </div>
        <% if @sessions_array.empty? %>
          <p class="d-flex w-100 justify-content-center font-italic mt-3">Currently not registered for any hack sessions.</p>
        <% else %>
          <% @sessions_array.reverse.each do |h| %>
            <div class="container-card">
              <div class="row align-items-center">
                <div class="col-xl-5">
                  <div class="box-card">
                    <img src="<%= h.project.cover_photo.url %>" class="card-image" alt="">
                  </div>
                </div>
                <div class="col-xl-7">
                  <div class="box-card-content">
                    <p><strong>Project:</strong> <%= h.project.name %></p>
                    <p><strong>Location:</strong> <%= h.address %></p>
                    <p><strong>Time:</strong> <%= h.date %></p>
                    <div class="avatar-list">
                      <% h.attendants.each do |attendant| %>
                        <% user_instance = User.find(attendant) %>
                        <%= link_to user_path(attendant) do %>
                          <img src="<%= user_instance.profile_avatar_url %>" class="avatar" data-toggle="tooltip" data-placement="top" title="<%= user_instance.username %>">
                        <% end %>
                      <% end %>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
        </div>



      </div>
    </div>
  </div>
</div>


<br />
<br />
<% if false %>
<% if @sessions_array.empty? == false %>
  <% @sessions_array.each do |h| %>
    <%= cl_image_tag h.project.cover_photo%>
    <%= h.project.name %>
    <%= h.address %>
    <%= h.date %>
  <% end %>
<% end %>
<% end %>






<!-- Eliminate Show Duplicates -->
<%# guest_collabs = [] %>
  <%# @user.collaborations.each do |collab| %>
    <%# cid = collab.project_id %>
    <%# @user.projects.each do |p| %>
      <%# if cid != p.id %>
        <%# p %>
        <%# guest_collabs << p %>
      <%# end %>
    <%# end %>
  <%# end %>
<%# if guest_collabs.empty? %>