config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects do
    resources :collaborations, only: [:new, :create, :show, :index]

    resources :comments, only: [:index, :show, :new, :create]
    resources :hacker_days, only: [:new, :create, :show, :update,:destroy, :index]
    resources :likes
    resources :team_comments, only: [:index, :show, :new, :create]

  end

  resources :users, only: :show do
    resources :notifications, only: :index
  end

  post 'users/:user_id/notifications', to: 'notifications#mark_as_read', as: :notifications_mark_as_read


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :show ]
      resources :projects, only: [ :index, :show, :update, :create, :destory ] do
        resources :hacker_days, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :comments, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :likes, only: [ :index, :show, :new, :create, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="list-icons">
    <a href="#"><i class="fab fa-facebook-square"></i></a>
    <a href="#"><i class="fab fa-github-square"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-weixin"></i></a>
  </div>
  <p>Coded with ❤️ at Le Wagon</p>
</div>

app/views/shared/_navbar.html.erb
<div class="pos-f-t">
  <nav class="navbar navbar-expand-md navbar-dark bg-dark py-0">
    <%= link_to "/", class: "navbar-brand d-flex align-items-center" do %>
      <%= image_tag "hackeroasis.svg", height: "20px" %>
    <% end %>
    <div class="box-togglers">
      <button type="button" class="navbar-toggler my-2 toggler-icon" data-target="#learnMoreModal" data-toggle="modal" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation" data-keyboard="false">
        <i class="fas fa-info-circle"></i>
      </button>
      <button type="button" class="navbar-toggler my-2 toggler-icon" data-target="#indexMap" data-toggle="modal" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-map"></i>
      </button>
      <button class="navbar-toggler my-2" type="button" data-toggle="collapse" data-target="#navbarToggleExternalContent" aria-controls="navbarToggleExternalContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>

    <div class="collapse navbar-collapse justify-content-between" id="navbarExpandedContent">

      <div class="box-search">
        <%= form_tag('/projects', method: :get, class: "form-inline my-2 my-lg-0" ) do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-sm-2",
            type: "search",
            'aria-label': "Search",
            placeholder: "Find a project..."
          %>
          <%= submit_tag "Search", class: "btn btn-outline-secondary my-2 my-sm-0", type: "submit" %>
        <% end %>
      </div>

      <div class="container-user">
        <% if user_signed_in? %>

          <div class="dropdown-avatar">
            <img class="avatar-medium dropbtn" src="<%= current_user.profile_avatar_url %>"/>
            <div class="dropdown-content">
              <div class="dropdown-container">
                <%= link_to "Profile", user_path(current_user), class: "dropdown-item" %>
              </div>
              <div class="dropdown-container">
                <%= link_to "Add Project", new_project_path, class: "dropdown-item" %>
              </div>
              <div class="dropdown-divider"></div>
              <div class="dropdown-container">
                <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
              </div>
              <div class="dropdown-container">
                <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
              </div>
            </div>
          </div>
          <div class="dropdown-notifications">
            <a class="dropdown-toggle nav-link p-0" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <i class="fas fa-bell"></i>
            </a>
            <% if current_user.notifications.unread.size > 0 %>
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdownMenuLink">
                <div class="box-notifications">
                  <% current_user.notifications.unread.order(created_at: :desc).each do |noti| %>
                    <a class="dropdown-item" href="../../projects/<%= noti.notifiable.id %>"> <img src="<%= noti.actor.profile_avatar_url %>" class="avatar"> <strong><%= noti.actor.username %></strong> <%= noti.action %> "<%= noti.notifiable.name %>" <em><%= distance_of_time_in_words(Time.now - noti.created_at) %> ago</em></a>
                  <% end %>
                </div>
                <%= link_to notifications_mark_as_read_path(current_user), class: "dropdown-item", method: :post do %>
                  <center>Mark all as read</center>
                <% end %>
              </div>
              <% if current_user.notifications.unread.size > 99 %>
                <div class="badge-red-triple"><%= current_user.notifications.unread.size %></div>
              <% elsif current_user.notifications.unread.size > 9 %>
                <div class="badge-red-double"><%= current_user.notifications.unread.size %></div>
              <% elsif current_user.notifications.unread.size > 0 %>
                <div class="badge-red"><%= current_user.notifications.unread.size %></div>
              <% else %>
                <span></span>
              <% end %>
            <% else %>
              <div class="dropdown-menu dropdown-menu-right"aria-labelledby="dropdownMenuLink">
                <a class="dropdown-item" href="#">You have no new notifications at this time</a>
              </div>
            <% end %>
          </div>
        <% else %>
          <div class="box-nav-links">
              <%= link_to "Login", new_user_session_path %>
              <span style="border-right: 1px solid rgba(229,229,229,0.2); margin-right: 8px;"></span>
              <%= link_to "Sign Up", new_user_registration_path%>
          </div>
        <% end %>
      </div>

    </div>
  </nav>

  <div class="collapse" id="navbarToggleExternalContent">
    <div class="bg-dark p-3">
      <div class="toggle-box-search">
       <%= form_tag('/projects', method: :get, class: "form-inline my-2 my-lg-0" ) do %>
          <%= text_field_tag :query,
            params[:query],
            class: "form-control mr-sm-2",
            type: "search",
            'aria-label': "Search",
            placeholder: "Find a project..."
          %>
          <%= submit_tag "Search", class: "btn btn-outline-secondary my-2 my-sm-0", type: "submit" %>
        <% end %>
      </div>
      <% if user_signed_in? %>
        <div class="toggle-box-avatar">
          <%= link_to user_path(current_user) do %>
            <img class="avatar-medium" src="<%= current_user.profile_avatar_url %>"/>
            <h5><%= current_user.username %></h5>
          <% end %>

          <div class="toggle-item">
            <a data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample">
              Notifications <span class="badge badge-light" style="margin-left: 4px;"><%= current_user.notifications.unread.size %></span>
            </a>
          </div>
          <div class="collapse" id="collapseExample">
            <div class="toggle-item">
              <% if current_user.notifications.unread.size > 0 %>
                <div class="responsive-notifications">
                  <% current_user.notifications.unread.order(created_at: :desc).each do |noti| %>
                    <a href="../../projects/<%= noti.notifiable.id %>"> <img src="<%= noti.actor.profile_avatar_url %>" class="avatar-small"><%= noti.action %> "<%= noti.notifiable.name %>" <em><%= distance_of_time_in_words(Time.now - noti.created_at) %> ago</em></a>
                  <% end %>
                </div>
                <%= link_to notifications_mark_as_read_path(current_user), method: :post do %>
                  <span style="font-size: 12px;">Mark all as read</span>
                <% end %>
              <% else %>
                <a href="#" style="font-size: 12px;">You have no new notifications at this time</a>
              <% end %>
            </div>
          </div>
          <div class="toggle-item">
            <%= link_to "Profile", user_path(current_user) %>
          </div>
          <div class="toggle-item">
            <%= link_to "Add Project", new_project_path %>
          </div>
        </div>
        <div class="toggle-item">
          <%= link_to "Account Settings", edit_user_registration_path %>
        </div>
        <div class="toggle-item">
          <%= link_to "Log out", destroy_user_session_path, method: :delete %>
        </div>
      <% else %>
        <div class="toggle-item">
          <%= link_to "Login", new_user_session_path %>
        </div>
        <div class="toggle-item">
          <%= link_to "Sign Up", new_user_registration_path %>
        </div>
      <% end %>
    </div>

  </div>
</div>

<!-- Nav Modals -->

<div class="modal fade" id="learnMoreModal" tabindex="-1" role="dialog" aria-labelledby="hackerDayModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="learnMoreModalLabel">What's a Hack Session?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Project owners can schedule hack sessions for their projects, and anyone can join.</p>

        <p>Think of hack sessions as mini-hackathons that last one full day (8-12 hours), where you work together to build a minimum viable product (MVP) or a new feature for an existing digital product.</p>
      </div>
    </div>
  </div>
</div>