config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects do
    resources :collaborations, only: [:new, :create, :show, :index]

    resources :comments, only: [:index, :show, :new, :create]
    resources :hacker_days, only: [:new, :create, :show, :update,:destroy, :index]
    resources :likes
    resources :team_comments, only: [:index, :show, :new, :create]

  end

  resources :users, only: :show do
    resources :notifications, only: :index
  end

  post 'users/:user_id/notifications', to: 'notifications#mark_as_read', as: :notifications_mark_as_read


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :show ]
      resources :projects, only: [ :index, :show, :update, :create, :destory ] do
        resources :hacker_days, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :comments, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :likes, only: [ :index, :show, :new, :create, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project.rb
class Project < ApplicationRecord
  acts_as_taggable_on :tags
  mount_uploader :cover_photo, PhotoUploader
  belongs_to :user
  has_many :collaborations, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy
  # validates :name, :description, :cover_photo, :photo1, presence: true
  has_many :hacker_days, dependent: :destroy
  # geocoded_by :location
  # after_validation :geocode, if: :will_save_change_to_location?

  # validates :name, :description, :cover_photo, :photo1, presence: true

  include PgSearch
  pg_search_scope :multisearchable,
    against: [ :name, :description ],
    associated_against: {
      user: [ :first_name, :last_name, :city, :country, :description, :username ]
    },
    using: {
      tsearch: {prefix: true}
    }
end

app/controllers/api/v1/projects_controller.rb
class Api::V1::ProjectsController < Api::V1::BaseController
  before_action :set_project, only: [ :show, :update ]
  def index
    @projects = Project.all
    # render json: @projects #Just for testing
  end

  def show
  end

  def update
    if @project.update(project_params)
      render :show
    else
      render_error
    end
  end

  def create
    @project = Project.new(project_params)
    if @project.save
      render :show, status: :created
    else
      render_error
    end
  end

  def destroy
    @project.destroy
    head :no_content
  end

  private

  def set_project
    @project = Project.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name, :description, :cover_photo)
  end

  def render_error
    render json: { errors: @project.errors.full_messages },
    status: :unprocessable_entity
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]
  before_action :set_project, only: [:show, :update, :destroy, :edit]
  skip_after_action :verify_policy_scoped, :only => :index

  def index
    if params[:query].present?
      @projects = Project.multisearchable(params[:query])
    else
      @projects = policy_scope(Project).order(created_at: :desc)
    end
    @hacker_days = HackerDay.geocoded
    @markers = @hacker_days.map do |hacker_day|
      {
        lat: hacker_day.latitude,
        lng: hacker_day.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { hacker_day: hacker_day }),
        image_url: helpers.asset_url('https://icon-library.net/images/laptop-icon-png-transparent/laptop-icon-png-transparent-9.jpg')
      }
    end
    @hacker_days = HackerDay.all
    # @sessions_array =
    # HackerDay.all.each do |x|
    #   if x.project_id.include?(project_id)
    #     @sessions_array << x
    #   end
    # end

  end

  def new
    @project = Project.new
    authorize @project
  end

  def create
    @project = Project.new(project_params)
    @project.user = current_user
    authorize @project
    if @project.save
      # Collaboration.create(user_id: current_user.id, project_id: @project.id)
      redirect_to root_path
    else
      render 'new'
    end
  end

  def update
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    @project.destroy
    redirect_to projects_path
  end

  def edit
  end

  def show
    @hacker_days = HackerDay.where(project_id: @project.id)
    @hacker_day = @hacker_days.last
    @comment = Comment.new
    @comments = @project.comments
    @team_comment = TeamComment.new
    # @collaboration = Collaboration.new
    # @users = User.all.order(username: :asc)
    @users = User.all.order(username: :asc).map{ |user| user.username }

    if @hacker_day.present?
      @marker = [
        { lat: @hacker_day.latitude,
          lng: @hacker_day.longitude,
          infoWindow: render_to_string(partial: "info_window_show", locals: { hacker_day: @hacker_day })
        }]
    end
  end

  private

  def project_params
    params.require(:project).permit(:name, :description, :cover_photo, :cover_photo_cache, :url, :qrcode, :type, tag_list: [])
  end

  def set_project
    @project = Project.find(params[:id])
    authorize @project
  end
end

app/views/projects/_collaborators.html.erb
<h6 style="margin:0;">Project Collaborators</h6>

<div class="box-collaborators">
  <i class="fas fa-users"></i>
  <div class="avatar-list">
    <% @project.collaborations.map do |collaboration| %>
      <%= link_to user_path(collaboration.user) do %>
        <img src="<%= collaboration.user.avatar.url(:bright_face) %>" class="avatar-small" data-toggle="tooltip" data-placement="top" title="<%= collaboration.user.username %>">
      <% end %>
    <% end %>
  </div>
</div>
<% if policy(@project).update? %>
  <%= simple_form_for [@project, @collaboration] do |f| %>
    <%= f.input :user, collection: @users, label: false %>
    <%= f.button :submit, "Add Collaborator", class: "btn-social" %>
  <% end %>
<% end %>

app/views/projects/_info_window.html.erb
<h5><%= link_to hacker_day.project.name, project_path(hacker_day.project) %></h5>
<p>Date: <%= hacker_day.date.strftime('%A, %d %b %Y %l:%M %p') %></p>
<p>Location: <%= hacker_day.address %></p>
<p>Hackers Attending: <%= hacker_day.attendants.count %></p>

app/views/projects/_info_window_show.html.erb
<p style="margin: 0; padding: 8px 0 0 0;">See you there!</p>

app/views/projects/_learn_more.html.erb
<div class="modal fade" id="learnMoreModal" tabindex="-1" role="dialog" aria-labelledby="hackerDayModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="learnMoreModalLabel">What's a Hack Session?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <p>Project owners can schedule hack sessions for their projects, and anyone can join.</p>

        <p>Think of hack sessions as mini-hackathons that last one full day (8-12 hours), where you work together to build a minimum viable product (MVP) or a new feature for an existing digital product.</p>
      </div>
    </div>
  </div>
</div>

app/views/projects/_new_hack_session.html.erb
<div class="modal fade" id="hackerDayModal" tabindex="-1" role="dialog" aria-labelledby="hackerDayModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="hackerDayModalLabel">Create Hack Session</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <div class="modal-body">
        <% @hacker_day = HackerDay.new %>
        <%= simple_form_for [@project, @hacker_day] do |f| %>
          <%= f.input :date, label: "When will you hack?", input_html: {class: "dateSelection"}, as: :string %>
          <%= f.input :address, label: "Where will the hacking take place?", :input_html => { id: "hacker_day_address" } %>
          <%= f.button :submit, "HackSession.new", class: "btn-signup" %>
          <%= f.button :button, "Reset", type: "reset", class: "btn-reset" %>
        <% end %>
      </div>
    </div>
  </div>
</div>


<script>
  document.addEventListener('DOMContentLoaded', function() {
    flatpickr(".dateSelection", {
         enableTime: true,
         minDate: "today"
    });
        // console.log('here')
  })
</script>

app/views/projects/_public_chat.html.erb
<%= simple_form_for [@project, @comment], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "What are your thoughts?" %>
  <%= f.button :submit, "Comment", class: "btn-social" %>
<% end %>
<div class="number-comments">
  <h6><%= @project.comments.size %> comments</h6>
</div>
<div class="box-comment-messages">
  <% @project.comments.order(id: :desc).each do |c| %>
    <div class="comment-header">
      <img src="<%= c.user.profile_avatar_url %>" class="avatar">
      <p><%= link_to c.user.username, user_path(c.user) %> <em><%= distance_of_time_in_words(Time.now - c.created_at) %> ago</em></p>
    </div>
    <div class="comment-content">
      <p><%= c.content %></p>
    </div>
  <% end %>
</div>

app/views/projects/_team_chat.html.erb
<%= simple_form_for [@project, @team_comment], remote: true do |f| %>
  <%= f.input :content, label: false, placeholder: "What are your thoughts?" %>
  <%= f.button :submit, "Comment", class: "btn-social" %>
<% end %>
<div class="number-team-comments">
  <h6><%= @hacker_day.team_comments.size %> comments</h6>
</div>

<div class="box-team-comment-messages">
  <% @hacker_day.team_comments.order(id: :desc).each do |c| %>
    <div class="comment-header">
      <img src="<%= c.user.profile_avatar_url %>" class="avatar">
      <p><%= link_to c.user.username, user_path(c.user) %> <em><%= distance_of_time_in_words(Time.now - c.created_at) %> ago</em></p>
    </div>
    <div class="comment-content">
      <p><%= c.content %></p>
    </div>
  <% end %>
</div>

app/views/projects/_waves_animation.html.erb
<!-- waves animation -->
 <svg class="waves" width="192" height="18" viewBox="0 0 192 18" fill="none" xmlns="http://www.w3.org/2000/svg" style="">
<path d="M1 5.80062C13.218 -13.2354 10.096 32.3006 24.5 5.80062C36.718 -13.2354 34.596 32.3006 49 5.80062C61.925 -13.2354 60.096 32.3006 74.5 5.80062" stroke="#3A8BBB" stroke-width="2" class="idPzwKXV_0"></path>
<path d="M117 7.80062C129.218 -11.2354 126.096 34.3006 140.5 7.80062C152.718 -11.2354 150.596 34.3006 165 7.80062C177.925 -11.2354 176.096 34.3006 190.5 7.80062" stroke="#3A8BBB" stroke-width="2" class="idPzwKXV_1"></path>
<style data-made-with="vivus-instant">.idPzwKXV_0{stroke-dasharray:114 116;stroke-dashoffset:115;animation:idPzwKXV_draw_0 13200ms linear 0ms infinite,idPzwKXV_fade 13200ms linear 0ms infinite;}.idPzwKXV_1{stroke-dasharray:114 116;stroke-dashoffset:115;animation:idPzwKXV_draw_1 13200ms linear 0ms infinite,idPzwKXV_fade 13200ms linear 0ms infinite;}@keyframes idPzwKXV_draw{100%{stroke-dashoffset:0;}}@keyframes idPzwKXV_fade{0%{stroke-opacity:1;}96.96969696969697%{stroke-opacity:1;}100%{stroke-opacity:0;}}@keyframes idPzwKXV_draw_0{6.0606060606060606%{stroke-dashoffset: 115}43.93939393939394%{ stroke-dashoffset: 0;}100%{ stroke-dashoffset: 0;}}@keyframes idPzwKXV_draw_1{43.93939393939394%{stroke-dashoffset: 115}81.81818181818183%{ stroke-dashoffset: 0;}100%{ stroke-dashoffset: 0;}}</style></svg>

<!-- end of waves animation -->

app/views/projects/edit.html.erb
<div class="submenu-tall" style="justify-content: center">
  <h4 class="sub-header">Edit project details</h4>
</div>

<div class="container">
  <div class="row form-add-project">
    <div class="col-lg-8">
      <div class="form-box">
        <%= simple_form_for @project do |f| %>
          <%= f.input :name %>
          <%= f.input :description %>
          <%= f.input :cover_photo, label: "Landing Page Screenshot" %>
          <%= f.input :cover_photo_cache, as: :hidden %>
          <%= f.input :project_type, as: :radio_buttons, label: "Project Type", collection: ["Mobile", "Web", "Both"], wrapper: :vertical_collection_inline %>
          <%= f.input :url, label: "Project Link" %>
          <%= f.label :name, "Project Categories (ex. blockchain, javascript, ruby, wechat, etc.)" %>
          <div data-tags-input-name="project[tag_list]" id="tag"></div>
          <p>Press enter, comma or spacebar to create a new tag; backspace or delete to remove.</p>
          <%= f.button :submit, "Update", class: "btn-signup" %>
        <% end -%>
      </div>
    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="submenu-tall" style="justify-content: center">
  <h4 class="sub-header">What are you working on?</h4>
</div>

<div class="container">
  <div class="row form-add-project">
    <div class="col-lg-8">
      <div class="form-box">
        <%= simple_form_for @project do |f| %>
          <%= f.input :name, autofocus: true, label: "Project Name" %>
          <%= f.input :description, label: "Short Project Description" %>
          <%= f.input :cover_photo, label: "Landing Page Screenshot" %>
          <%= f.input :cover_photo_cache, as: :hidden %>
          <%= f.input :project_type, as: :radio_buttons, label: "Project Type", collection: ["Mobile", "Web", "Both"], wrapper: :vertical_collection_inline %>
          <%= f.input :url, label: "Project Link" %>
          <%= f.label :name, "Project Categories (ex. blockchain, javascript, ruby, wechat, etc.)" %>
          <div data-tags-input-name="project[tag_list]" id="tag"></div>
          <p>Press enter, comma or spacebar to create a new tag; backspace or delete to remove.</p>
          <%= f.button :submit, "Project.new", class: "btn-signup" %>
          <%= f.button :button, "Reset", type: "reset", class: "btn-reset" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/projects/show.html.erb
<div class="body-container">
  <!-- Headline -->

  <div class="submenu-tall" style="justify-content: center">
    <h4 class="sub-header">Help <%= @project.user.username %>'s project become better</h4>
  </div>

  <!-- Project owner information and like/follow buttons -->

  <div class="container">
    <div class="row" style="justify-content: center;">
      <div class="col col-sm-12 col-lg-8">
        <div class="submenu-show">
          <img src="<%= @project.user.profile_avatar_url %>" class="avatar-large">
          <div class="project-details">
            <h4><%= @project.name %></h4>
            <p>by <%= link_to @project.user.username, user_path(@project.user) %>
            </p>
          </div>
          <% if Like.where(user: current_user, project: @project).exists? %>
            <%= link_to project_like_path(@project, @project.user.likes), method: :delete do %>
              <div class="btn-social-red toggle-social"><i class="fas fa-heart"></i> Liked</div>
            <% end %>
          <% else %>
            <%= link_to project_likes_path(@project), method: :post do %>
              <div class="btn-social-like toggle-social"><i class="fas fa-heart"></i> Like</div>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <hr>

  <!-- Project image(s) -->

  <div class="container">
    <div class="row" style="justify-content: center;">
      <div class="col-lg-8">
        <%= cl_image_tag(@project.cover_photo, class: "project-photo") %>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row" style="justify-content: center;">
    <div class="col-lg-8">
      <div class="container-description">
        <div class="row" style="width: 100%;">
          <div class="col-md-8">
            <div class="box-description">
              <div class="text-description">
                <%= simple_format(@project.description) %>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="icons-project-crud">
              <% if policy(@project).edit? %>
                <%= link_to edit_project_path(@project) do %>
                    <i class="fas fa-edit icon" data-toggle="tooltip" data-placement="top" title="Edit project details"></i>
                <% end %>
              <% end %>
              <% if policy(@project).destroy? %>
                <%= link_to project_path(@project), method: 'delete', data: { confirm: "Are you sure?" } do %>
                    <i class="far fa-trash-alt icon" data-toggle="tooltip" data-placement="top" title="Delete project"></i>
                <% end %>
              <% end %>
            </div>
            <div class="box-project-public">
              <%= link_to "http://#{@project.url}" , :target => "_blank", rel: "nofollow" do %>
              <i class="fas fa-link" style="padding-right: 6px;"></i>
              <p>Project link</p>
              <% end %>
              <%= link_to "#" do %>
                <i class="fab fa-github-square"></i>
                <p>Project repository</p>
              <% end %>
              <%= link_to "#" do %>
                <i class="fas fa-envelope-square"></i>
                <p>Contact project owner</p>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="row" style="justify-content: center;">
    <div class="col-lg-8">
      <div class="container-description">
        <div class="row" style="width: 100%;">
          <div class="col-md-8">
            <div class="box-hacksession">
              <% if @hacker_days.empty? == false %>
                <% @att = @hacker_days.last.attendants %>
                <% if current_user.nil? == false && @att.include?(current_user.id.to_s) == false %>
                  <h6>Next Hack Session</h6>
                  <p><strong>Date and time: </strong><%= @hacker_days.last.date.strftime('%A, %d %b %Y %l:%M %p') %>
                  <br />
                  <strong>Address: </strong><%= @hacker_days.last.address %></p>
                  <h6 style="margin:0;">Hack Team</h6>
                  <div class="box-collaborators">
                    <i class="fas fa-users"></i>
                    <div class="avatar-list">
                      <% @project.hacker_days.map do |hacker_day| %>
                        <% hacker_day.attendants.each do |attendant| %>
                          <%= link_to user_path(attendant) do %>
                            <img src="<%= User.find(attendant).profile_avatar_url %>" class="avatar" data-toggle="tooltip" data-placement="top" title="<%= User.find(attendant).username %>">
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>

                  <%= simple_form_for [@project, @hacker_days.last], method: 'put' do |f| %>
                    <% @hacker_days.last.attendants.each do |uid| %>
                      <%= f.hidden_field :attendants, value: uid, multiple: true %>
                    <% end %>
                    <%= f.hidden_field :attendants, value: current_user.id, multiple: true %>
                    <%= f.button :submit, "Join", class: "btn-signup" %>
                  <% end %>

                <% elsif current_user.nil? %>
                  <p>Please login to join hack sessions!</p>
                <% else %>

                  <p>Registered to the next hack session on <em><%= @hacker_days.last.date.strftime('%A, %d %b %Y %l:%M %p') %></em> at <strong><%= @hacker_days.last.address %>.</strong></p>
                  <h6 style="margin:0;">Hack Team</h6>
                  <div class="box-collaborators">
                    <i class="fas fa-users"></i>
                    <div class="avatar-list">
                      <% @project.hacker_days.map do |hacker_day| %>
                        <% hacker_day.attendants.each do |attendant| %>
                          <%= link_to user_path(attendant) do %>
                            <img src="<%= User.find(attendant).profile_avatar_url %>" class="avatar" data-toggle="tooltip" data-placement="top" title="<%= User.find(attendant).username %>">
                          <% end %>
                        <% end %>
                      <% end %>
                    </div>
                  </div>

                <% end %>
              <% else %>
                <p>Currently no hack session scheduled for this project.</p>
              <% end %>

              <!-- Create Hacker Day Modal -->

              <% if policy(@project).edit? && (@project.hacker_days.empty? || DateTime.now > @project.hacker_days.last.date) %>
                <button type="button" class="btn btn-signup" data-toggle="modal" data-target="#hackerDayModal" >
                  HackSession.new
                </button>
              <% end %>

              <!-- Delete Hack Session -->

              <% if policy(@project).edit? && (@hacker_day.nil? == false) %>
                <%= link_to project_hacker_day_path(@project, @hacker_day), method: 'delete', class: 'btn-signup', data: { confirm: "Are you sure?" } do %>
                    HackSession.destroy
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="col-md-4">
            <div class="box-hack-info">
              <div id="map" style="width: 100%; height: 160px" data-markers="<%= @marker.to_json %>" data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<div class="container">
  <div class="row" style="justify-content: center;">
    <div class="col-lg-8">
      <div class="container-description">
        <div class="row" style="width: 100%;">
          <div class="col-md-8">
            <div class="box-comments">

              <!-- Nav tabs -->
              <ul class="nav nav-tabs" id="commentTab" role="tablist">
                <li class="nav-item">
                  <a class="nav-link active" id="public-chat-tab" data-toggle="tab" href="#public-chat" role="tab" aria-controls="public-chat" aria-selected="true">Public Chat</a>
                </li>
                <% if @hacker_days.empty? == false %>
                  <% @att = @hacker_days.last.attendants %>
                  <% if current_user.nil? == false && @att.include?(current_user.id.to_s) %>
                    <li class="nav-item">
                      <a class="nav-link" id="team-chat-tab" data-toggle="tab" href="#team-chat" role="tab" aria-controls="team-chat" aria-selected="false">Team Chat</a>
                    </li>
                  <% end %>
                <% end %>
              </ul>

              <!-- Tab panes -->
              <div class="tab-content">
                <div class="tab-pane active" id="public-chat" role="tabpanel" aria-labelledby="public-chat-tab">
                  <%= render 'public_chat' %>
                </div>
                <div class="tab-pane" id="team-chat" role="tabpanel" aria-labelledby="team-chat-tab">
                  <% if @hacker_days.empty? == false %>
                    <%= render 'team_chat' %>
                  <% end %>
                </div>
              </div>
            </div>
          </div>

          <div class="col-md-4">
            <div class="box-tags">
              <i class="fas fa-tag"></i>
              <div class="tags">
                <% @project.tag_list.each do |t| %>
                <span><%= link_to t, "#" %></span>
                <% end %>
              </div>
            </div>
            <div class="box-likes">
              <i class="fas fa-heart"></i>
              <p><%= @project.likes.count %> <%= (@project.likes.count) == 1 ? 'Like' : 'Likes'%></p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->

<%= render 'new_hack_session' %>



<!-- Event Listeners -->

<!-- Public Chat JavaScript -->
<script>
  const commentForm = document.querySelector("#new_comment");
  const commentList = document.querySelector(".box-comment-messages");
  const numberComments = document.querySelector(".number-comments");
  let commentSize = `<%= @project.comments.size %>`;

  const showComment = (id) => {
    Rails.ajax({
      url: `/projects/<%= @project.id %>/comments/${id}`,
      type: "get",
      data: ""
    })
  };

  const listComments = (data) => {
    i = 0
    data.forEach((comment) => {
      i ++;
      if (i > commentSize) {
        commentSize = comment.id;
        showComment(comment.id);
        numberComments.innerHTML = `<h6>${i} comments</h6>`
      }
    });
  };

  const getComments = () => {
    Rails.ajax({
      url: "<%= project_comments_path(@project.id) %>",
      type: "get",
      data: "",
      success: function(data) {
        listComments(data);
      },
      error: function(data) {
        console.log(data);
      }
    })
  };


  commentForm.addEventListener('ajax:success', (e) => {
    commentSize = parseInt(commentSize) + 1;
    getComments();
    numberComments.innerHTML = `<h6>${commentSize} comments</h6>`
  });

  document.addEventListener("DOMContentLoaded", () => {
    setInterval(getComments, 2000);
  });

</script>

<!-- Team Chat JavaScript -->
<% if @project.hacker_days.empty? == false %>
  <script>
    const teamCommentForm = document.querySelector("#new_team_comment");
    const teamCommentList = document.querySelector(".box-team-comment-messages");
    const numberTeamComments = document.querySelector(".number-team-comments");
    let teamCommentSize = `<%= @project.hacker_days.last.team_comments.size %>`;
    console.log(teamCommentSize);

    const showTeamComment = (id) => {
      Rails.ajax({
        url: `/projects/<%= @project.id %>/team_comments/${id}`,
        type: "get",
        data: ""
      })
    };

    const listTeamComments = (data) => {
      i = 0
      data.forEach((team_comment) => {
        i ++;
        if (i > teamCommentSize) {
          teamCommentSize = team_comment.id;
          showTeamComment(team_comment.id);
          numberTeamComments.innerHTML = `<h6>${i} comments</h6>`
        }
      });
    };

    const getTeamComments = () => {
      Rails.ajax({
        url: "<%= project_team_comments_path(@project.id) %>",
        type: "get",
        data: "",
        success: function(data) {
          listTeamComments(data);
        },
        error: function(data) {
          console.log(data);
        }
      })
    };


    teamCommentForm.addEventListener('ajax:success', (e) => {
      teamCommentSize = parseInt(teamCommentSize) + 1;
      getTeamComments();
      numberTeamComments.innerHTML = `<h6>${teamCommentSize} comments</h6>`
    });

    document.addEventListener("DOMContentLoaded", () => {
      setInterval(getTeamComments, 2000);
    });

  </script>
<% end %>

<!-- Add eventListener for btn when create hacker session to open calendar -->

<!-- End -->