config/routes.rb
Rails.application.routes.draw do
  root to: 'projects#index'

  devise_for :users,
    controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :projects do
    resources :collaborations, only: [:new, :create, :show, :index]

    resources :comments, only: [:index, :show, :new, :create]
    resources :hacker_days, only: [:new, :create, :show, :update,:destroy, :index]
    resources :likes
    resources :team_comments, only: [:index, :show, :new, :create]

  end

  resources :users, only: :show do
    resources :notifications, only: :index
  end

  post 'users/:user_id/notifications', to: 'notifications#mark_as_read', as: :notifications_mark_as_read


  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: [ :show ]
      resources :projects, only: [ :index, :show, :update, :create, :destory ] do
        resources :hacker_days, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :comments, only: [ :index, :show, :new, :create, :update, :destroy]
        resources :likes, only: [ :index, :show, :new, :create, :destroy]
      end
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/hacker_day.rb
class HackerDay < ApplicationRecord
  belongs_to :project
  has_many :team_comments, dependent: :destroy
  geocoded_by :address
  validates :address, :date, presence: true
  after_validation :geocode, if: :will_save_change_to_address?

  def users
    User.where(id: attendants)
  end
end

app/controllers/api/v1/hacker_days_controller.rb
class Api::V1::HackerDaysController < Api::V1::BaseController

  def index
    @hacker_days = HackerDay.all
  end

  def show
    @project = Project.find(params[:project_id])
    authorize @project
    @hacker_days = HackerDay.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    authorize @project
    @hacker_day = HackerDay.new
  end

  def create
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.new(params_hackerdays)
    @hacker_day.project = @project
    @project.user = current_user
    @hacker_day.attendants.push(current_user.id.to_s)
    authorize @project
    if @hacker_day.save
      redirect_to project_path(@project.id)
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.find(params[:id])
    authorize @hacker_day
    @hacker_day.update(params_hackerdays)
    if @hacker_day.update(params_hackerdays)
      noti = Notification.create(recipient: @project.user, actor: User.find(params_hackerdays["attendants"].last), action: "joined your hack session", notifiable: @project)
      # redirect_to project_hacker_day_path(@project.id, @hacker_day.id)
      redirect_to project_path(@project.id)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.find(params[:id])
    authorize @hacker_day
    @hacker_day.destroy
    redirect_to project_path(@project.id)
  end

  private

  def params_hackerdays
    params.require(:hacker_day).permit(:project_id, :user_id, :address, :longitude, :latitude, :date, attendants: [])
  end
end

app/controllers/hacker_days_controller.rb
class HackerDaysController < ApplicationController

  def index
    # @project = Project.find(params[:project_id])
    # authorize @project
    # where(project_id: @project.id).
  end

  def show
    @project = Project.find(params[:project_id])
    authorize @project
    @hacker_days = HackerDay.find(params[:id])
  end

  def new
    @project = Project.find(params[:project_id])
    authorize @project
    @hacker_day = HackerDay.new
  end

  def create
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.new(params_hackerdays)
    @hacker_day.project = @project
    @project.user = current_user
    @hacker_day.attendants.push(current_user.id.to_s)
    authorize @project
    if @hacker_day.save
      redirect_to project_path(@project.id)
    else
      render 'new'
    end
  end

  def update
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.find(params[:id])
    authorize @hacker_day
    @hacker_day.update(params_hackerdays)
    if @hacker_day.update(params_hackerdays)
      noti = Notification.create(recipient: @project.user, actor: User.find(params_hackerdays["attendants"].last), action: "joined your hack session", notifiable: @project)
      # redirect_to project_hacker_day_path(@project.id, @hacker_day.id)
      redirect_to project_path(@project.id)
    else
      render 'new'
    end
  end

  def destroy
    @project = Project.find(params[:project_id])
    @hacker_day = HackerDay.find(params[:id])
    authorize @hacker_day
    @hacker_day.destroy
    redirect_to project_path(@project.id)
  end

  private

  def params_hackerdays
    params.require(:hacker_day).permit(:project_id, :user_id, :address, :longitude, :latitude, :date, attendants: [])
  end
end

app/views/hacker_days/index.html.erb
<p>Hacker day Index page</p>

app/views/hacker_days/new.html.erb
<div class="submenu-tall" style="justify-content: center">
  <h4 class="sub-header">Seems like the form didn't go through. Please try again.</h4>
</div>

<%# simple_form_for @hacker_day, url: project_hacker_days_path(params[:project_id]) do |f| %>
<%# f.input :location, label: "Location" %>
<%# f.input :date, label: "Date" %>
<%# f.button :submit %>
<%# end %>
<div class="container">
  <div class="row form-add-project">
    <div class="col-lg-8">
      <div class="form-box">
        <%= simple_form_for [@project, @hacker_day] do |f| %>
          <%= f.input :date, label: "When will you hack?", input_html: {class: "dateSelection"}, as: :string %>
          <%= f.input :address, label: "Where will the hacking take place?", :input_html => { id: "hacker_day_address" } %>
          <%= f.button :submit, "HackSession.new", class: "btn-signup" %>
          <%= f.button :button, "Reset", type: "reset", class: "btn-reset" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<script>
  document.addEventListener('DOMContentLoaded', function() {
    flatpickr(".dateSelection", {
         enableTime: true,
         minDate: "today"
    });
        // console.log('here')
  })
</script>

app/views/hacker_days/show.html.erb
<p>Hacker Days Show page</p>

<% @hacker_day.users.each do |x| %>
<%= x.first_name%>
<%= x.username %>
<%= x.email %>

<% end %>